fail_fast: true
repos:
  - repo: local
    hooks:
      - id: custom-commit-msg
        name: Validate commit message format
        entry: scripts/githooks/commit-msg
        language: system
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: cms-check
        name: Run CMS code quality checks
        entry: devbox run just check
        language: system
        pass_filenames: false
        stages: [commit, push]
