name: Test Coverage

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  coverage:
    # Run on macOS for accurate coverage reporting (~82%)
    # - say provider is ready with full features
    # - espeak provider has limited coverage on macOS (tests skip)
    # - Linux compatibility is ensured by ci.yml matrix strategy
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          check-latest: true

      - name: Install Go modules
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests with coverage
        run: bash scripts/test-coverage.sh

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
